name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: docker login registry.digitalocean.com/so-thai -u "${{ secrets.DOCKER_KEY }}" -p "${{ secrets.DOCKER_KEY }}"

      - name: Build API Docker Image
        run: docker build -t "registry.digitalocean.com/so-thai/asset-tracker-api:latest" ./api

      - name: Build Frontend Docker Image
        run: docker build -t "registry.digitalocean.com/so-thai/asset-tracker-frontend:latest" .

      - name: Push API Docker Image to Registry
        run: docker push "registry.digitalocean.com/so-thai/asset-tracker-api:latest"

      - name: Push Frontend Docker Image to Registry
        run: docker push "registry.digitalocean.com/so-thai/asset-tracker-frontend:latest"

      - name: Logout from Registry
        run: docker logout
